INSERT INTO tb_user(email) VALUES ('maria@gmail.com');
INSERT INTO tb_user(email) VALUES ('joao@gmail.com');
INSERT INTO tb_user(email) VALUES ('ana@gmail.com');
INSERT INTO tb_user(email) VALUES ('lucia@gmail.com');
INSERT INTO tb_user(email) VALUES ('joaquim@gmail.com');

INSERT INTO tb_category(name) VALUES('Drama');
INSERT INTO tb_category(name) VALUES('Action');
INSERT INTO tb_category(name) VALUES('Animation');
INSERT INTO tb_category(name) VALUES('Comedy');
INSERT INTO tb_category(name) VALUES('Crime');
INSERT INTO tb_category(name) VALUES('Horror');
INSERT INTO tb_category(name) VALUES('Romance');
INSERT INTO tb_category(name) VALUES('Sci-Fi');
INSERT INTO tb_category(name) VALUES('Thriller');
INSERT INTO tb_category(name) VALUES('War');

INSERT INTO tb_movie(score, count, title, image, category_id) VALUES (4.5, 2, 'Interestelar', 'https://www.themoviedb.org/t/p/w500_and_h282_face/rAiYTfKGqDCRIIqo664sY9XZIvQ.jpg', 8);
INSERT INTO tb_movie(score, count, title, image, category_id) VALUES (3.3, 3, 'O Profissional', 'https://image.tmdb.org/t/p/original/jRJrQ72VLyEnVsvwfep8Xjlvu8c.jpg', 2);
INSERT INTO tb_movie(score, count, title, image, category_id) VALUES (0, 0, 'Meia Noite em Paris', 'https://www.themoviedb.org/t/p/w500_and_h282_face/zdsvY5RmPnZPx9U9yZa0b94m52x.jpg', 4);
INSERT INTO tb_movie(score, count, title, image, category_id) VALUES (0, 0, 'O Grande Truque', 'https://www.themoviedb.org/t/p/w500_and_h282_face/yCnJT53HMXAK87xzPAdjdYhZ3JE.jpg', 5);
INSERT INTO tb_movie(score, count, title, image, category_id) VALUES (0, 0, 'Um Estranho no Ninho', 'https://www.themoviedb.org/t/p/w500_and_h282_face/oje9d0EXQyQcxsqHQor4xFVGjrd.jpg', 1);
INSERT INTO tb_movie(score, count, title, image, category_id) VALUES (0, 0, 'Um Dia de Cão', 'https://www.themoviedb.org/t/p/w500_and_h282_face/g0NSjdH2eJgRaf7epUMQo8vRScv.jpg', 5);
INSERT INTO tb_movie(score, count, title, image, category_id) VALUES (0, 0, 'Beleza Americana', 'https://www.themoviedb.org/t/p/w500_and_h282_face/DztBnZaqmla2sGUW9s8AyOmskT.jpg', 1);
INSERT INTO tb_movie(score, count, title, image, category_id) VALUES (0, 0, 'Pulp Fiction: Tempo de Violência', 'https://www.themoviedb.org/t/p/w500_and_h282_face/suaEOtk1N1sgg2MTM7oZd2cfVp3.jpg', 5);
INSERT INTO tb_movie(score, count, title, image, category_id) VALUES (0, 0, 'Closer: Perto Demais', 'https://www.themoviedb.org/t/p/w500_and_h282_face/42vXbxmU8K28Z3ieGSbRiRoeI8W.jpg', 1);
INSERT INTO tb_movie(score, count, title, image, category_id) VALUES (0, 0, 'It: chapter 2', 'https://www.themoviedb.org/t/p/w500_and_h282_face/ycnDQVqHerSaQWQkemHcXOPOnA0.jpg', 6);
INSERT INTO tb_movie(score, count, title, image, category_id) VALUES (0, 0, 'Poderoso Chefão', 'https://www.themoviedb.org/t/p/w500_and_h282_face/rSPw7tgCH9c6NqICZef4kZjFOQ5.jpg', 5);
INSERT INTO tb_movie(score, count, title, image, category_id) VALUES (0, 0, 'Poderoso Chefão II', 'https://www.themoviedb.org/t/p/w500_and_h282_face/pKEQEqHSqkNDLMaXEulKWg3WcOm.jpg', 5);
INSERT INTO tb_movie(score, count, title, image, category_id) VALUES (0, 0, 'Poderoso Chefão III', 'https://www.themoviedb.org/t/p/w500_and_h282_face/csog0q5Ja1BS9ji3MeRRhzIgP22.jpg', 5);
INSERT INTO tb_movie(score, count, title, image, category_id) VALUES (0, 0, 'Donnie Darko', 'https://www.themoviedb.org/t/p/w500_and_h282_face/fULOsX1CoPQyGy4vGg4REsUbKSt.jpg', 9);
INSERT INTO tb_movie(score, count, title, image, category_id) VALUES (0, 0, 'Cruella', 'https://www.themoviedb.org/t/p/w500_and_h282_face/6MKr3KgOLmzOP6MSuZERO41Lpkt.jpg', 4);
INSERT INTO tb_movie(score, count, title, image, category_id) VALUES (0, 0, 'Psicopata Americano', 'https://www.themoviedb.org/t/p/w500_and_h282_face/xMnGZBGeR12qYjhOmg5WeWkUxdU.jpg', 9 );
INSERT INTO tb_movie(score, count, title, image, category_id) VALUES (0, 0, 'Bastardos Inglórios', 'https://www.themoviedb.org/t/p/w500_and_h282_face/bPnPsyo09tLRnTOb7AlsBsgnbhP.jpg', 'War' );
INSERT INTO tb_movie(score, count, title, image, category_id) VALUES (0, 0, 'Depois de Horas', 'https://www.themoviedb.org/t/p/w500_and_h282_face/7Pj9AZ4CpnxkDXYMxzae4WmJUsJ.jpg', 4);
INSERT INTO tb_movie(score, count, title, image, category_id) VALUES (0, 0, 'Em Ritmo de Fuga', 'https://www.themoviedb.org/t/p/w500_and_h282_face/yir5430WblZSZuIMd9C6pIZerfA.jpg', 5 );
INSERT INTO tb_movie(score, count, title, image, category_id) VALUES (0, 0, 'Um Sonho de Liberdade', 'https://www.themoviedb.org/t/p/w500_and_h282_face/9Xw0I5RV2ZqNLpul6lXKoviYg55.jpg', 1);
INSERT INTO tb_movie(score, count, title, image, category_id) VALUES (0, 0, 'Vicky Cristina Barcelona', 'https://www.themoviedb.org/t/p/w500_and_h282_face/dJ924xOo53Zmkf0dqbrbk3xE4e2.jpg', 7);
INSERT INTO tb_movie(score, count, title, image, category_id) VALUES (0, 0, 'Amnésia', 'https://www.themoviedb.org/t/p/w500_and_h282_face/7Wev9JMo6R5XAfz2KDvXb7oPMmy.jpg', 9);
INSERT INTO tb_movie(score, count, title, image, category_id) VALUES (0, 0, 'Meninas Malvadas', 'https://www.themoviedb.org/t/p/w500_and_h282_face/4qtXCsQglBx6fKYGOyj1un8mNIG.jpg', 4);
INSERT INTO tb_movie(score, count, title, image, category_id) VALUES (0, 0, 'Waking Life', 'https://www.themoviedb.org/t/p/w500_and_h282_face/56MLZww2dMVAaTt5LDKCBu1do2X.jpg', 3 );
INSERT INTO tb_movie(score, count, title, image, category_id) VALUES (0, 0, 'Adeus, Lênin!', 'https://www.themoviedb.org/t/p/w500_and_h282_face/elQ35lnbMHGgqx62kXqslL1ielY.jpg', 1);
INSERT INTO tb_movie(score, count, title, image, category_id) VALUES (0, 0, 'Má Educação', 'https://www.themoviedb.org/t/p/w500_and_h282_face/1tlXFhE6qnap6xvd4d4vzfHZpDZ.jpg', 1);
INSERT INTO tb_movie(score, count, title, image, category_id) VALUES (0, 0, 'Taxi Driver: Motorista de Táxi', 'https://www.themoviedb.org/t/p/w500_and_h282_face/byTvHqQIonluZT76enrwsehb9NW.jpg', 1);
INSERT INTO tb_movie(score, count, title, image, category_id) VALUES (0, 0, 'A Criada', 'https://1.bp.blogspot.com/-poLdxlfXJpM/XgZsHJoKlGI/AAAAAAAAWAQ/4MM4leParEIuSExH4KuNAPDh2qiJql0qwCLcBGAsYHQ/s1600/Review%2BA%2BCriada%2BThe%2BHandmaid%2BA-ga-ssi_12_27_2019.webp', 9);
INSERT INTO tb_movie(score, count, title, image, category_id) VALUES (0, 0, 'Gilbert Grape: Aprendiz de Sonhador', 'https://www.themoviedb.org/t/p/w500_and_h282_face/fHuKwcrwltGlWn3510N1YO7vJ4I.jpg', 1);  
INSERT INTO tb_movie(score, count, title, image, category_id) VALUES (0, 0, 'Tudo Sobre Minha Mãe', 'https://www.themoviedb.org/t/p/w500_and_h282_face/tilClWjFZeUTGJu0pxgF72fvUmN.jpg', 1);
INSERT INTO tb_movie(score, count, title, image, category_id) VALUES (0, 0, 'Babel', 'https://www.themoviedb.org/t/p/w500_and_h282_face/o2eG4ugPId4cY6gp2C1MBm33UG.jpg', 1);
INSERT INTO tb_movie(score, count, title, image, category_id) VALUES (0, 0, 'Birdman', 'https://www.themoviedb.org/t/p/w500_and_h282_face/pDqwUJJSaHIv2sxyRYfmYBFeU9C.jpg', 4);
INSERT INTO tb_movie(score, count, title, image, category_id) VALUES (0, 0, 'Fale com Ela', 'https://www.themoviedb.org/t/p/w500_and_h282_face/oJrOrkFd32Zau6HYZ4jJprqhzlc.jpg', 7);
INSERT INTO tb_movie(score, count, title, image, category_id) VALUES (0, 0, 'Contato', 'https://image.tmdb.org/t/p/w500_and_h282_face/yFkUPqBuUnbhYbQL8VFpTrAT9za.jpg', 8 );
INSERT INTO tb_movie(score, count, title, image, category_id) VALUES (0, 0, 'Sem Amor', 'https://www.themoviedb.org/t/p/w500_and_h282_face/wR1pvbWjAVEK9315ibedBwdyRLI.jpg', 1);
INSERT INTO tb_movie(score, count, title, image, category_id) VALUES (0, 0, 'O Operário', 'https://www.themoviedb.org/t/p/w500_and_h282_face/hi3lxLd93iKwCmVAfhMV9m1k2jr.jpg', 1);
INSERT INTO tb_movie(score, count, title, image, category_id) VALUES (0, 0, 'Dias Melhores', 'https://www.themoviedb.org/t/p/w500_and_h282_face/pi3yXaJzVxZUayUfqMekcsN199A.jpg', 1);
INSERT INTO tb_movie(score, count, title, image, category_id) VALUES (0, 0, 'Tenet', 'https://www.themoviedb.org/t/p/w500_and_h282_face/yY76zq9XSuJ4nWyPDuwkdV7Wt0c.jpg', 8);
INSERT INTO tb_movie(score, count, title, image, category_id) VALUES (0, 0, 'Era uma vez em... Hollywood', 'https://www.themoviedb.org/t/p/w500_and_h282_face/yB2hTgz9CTVYjlMWPSl3LPx5nWj.jpg', 4 );
INSERT INTO tb_movie(score, count, title, image, category_id) VALUES (0, 0, 'Sobre Meninos e Lobos', 'https://www.themoviedb.org/t/p/w500_and_h282_face/gLIf2TtQGhIPgpXBQ7yHN3nsduS.jpg', 9);
INSERT INTO tb_movie(score, count, title, image, category_id) VALUES (0, 0, 'Senhor Ninguém', 'https://www.themoviedb.org/t/p/w500_and_h282_face/8iYqLiWWdapOWxxMimSqtfST2M1.jpg', 8);
INSERT INTO tb_movie(score, count, title, image, category_id) VALUES (0, 0, 'Primavera, Verão, Outono, Inverno e... Primavera', 'https://www.themoviedb.org/t/p/w500_and_h282_face/95lyEbeqL6mDnJkmbLvgg2mFKM.jpg', 1);
INSERT INTO tb_movie(score, count, title, image, category_id) VALUES (0, 0, 'Dunkirk', 'https://www.themoviedb.org/t/p/w500_and_h282_face/4yjJNAgXBmzxpS6sogj4ftwd270.jpg', 10);

INSERT INTO tb_score(movie_id, user_id, value, comment ) VALUES (1, 1, 5.0, 'Ótimo filme');
INSERT INTO tb_score(movie_id, user_id, value, comment ) VALUES (1, 2, 4.0,'Gostei bastante');
INSERT INTO tb_score(movie_id, user_id, value, comment ) VALUES (2, 1, 3.0,'Não achei tão bom');
INSERT INTO tb_score(movie_id, user_id, value, comment ) VALUES (2, 2, 3.0,'Superestimado');
INSERT INTO tb_score(movie_id, user_id, value, comment ) VALUES (2, 3, 4.0,'Recomendo bastante');